name: Windows

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  run:
    runs-on: Windows-latest
    strategy:
      matrix:
        version:
          - "5.4.2"
          - "5.4.1"
          - "5.4"
  steps:
  - uses: actions/checkout@v2
  - uses: seanmiddleditch/gha-setup-vsdevenv@8c6bbf80998779f2bba87b1452832e561b65fd57
  - name: Install Swift
    uses: "."
    with:
      version: ${{ matrix.version }}
  - name: Test
    run: |
      mkdir build_test 
      cd build_test
      swift init --type executable
      swift run